language: python
if: branch = master
python: 3.6
services:
    - docker

jobs:
  include:
    - stage: Build recent x86_64 image
      script: make build ARCH=x86_64 GIT_TAG=${TRAVIS_TAG} PUSH=true

    - stage: Build recent ARM image
      script: make build ARCH=arm GIT_TAG=${TRAVIS_TAG} PUSH=true
